### ISSUE TITLE
Fails to parse

### ISSUE THREAD

**Issue by i-am-the-slime** [natefaubion/purescript-language-cst-parser#17]
```
module A where

data Bar = Baz (Boolean :: Type)
```

Results in `Unexpected '::' at { column: 24, line: 2 }`

It compiles, so I guess parsing should also work, right?

**Comment by natefaubion** [comment]
Thanks!
https://github.com/natefaubion/purescript-language-cst-parser/blob/0fa3a7a49e63b85895e50676e506a45f2aaffb08/src/PureScript/CST/Parser.purs#L514
This should be `parseType` instead of `parseType1` I believe.
