### ISSUE TITLE
Parser drops syntax on some errors.

### ISSUE THREAD

**Issue by natefaubion** [natefaubion/purescript-language-cst-parser#24]
Given this parse error (the second where should be indented):
```purescript
instance Class a where
  method = a
  where
  a = a
```

This gets parsed "successfully" as:
```purescript
instance Class a
  where
  a = a
```

**Comment by natefaubion** [comment]
I suspect this is related to this heavy-handed `optional`.
https://github.com/natefaubion/purescript-language-cst-parser/blob/bb36765e325a4ef5368ce5b7dcbb8cb7ed03affa/src/PureScript/CST/Parser.purs#L302

There's similar usage in classes that's probably just as bad:
https://github.com/natefaubion/purescript-language-cst-parser/blob/bb36765e325a4ef5368ce5b7dcbb8cb7ed03affa/src/PureScript/CST/Parser.purs#L266-L267

**Comment by garyb** [comment]
Yikes! I've not seen this one happen yet.

**Comment by natefaubion** [comment]
> edit: Oh, I see, it's occurring on a syntax error at least, not a valid code chunk.

Right, the source input is an error, however it's not parsed as a recovered error node (it's parsed successfully as an instance), which concerns me.

**Comment by natefaubion** [comment]
🤦 
https://github.com/natefaubion/purescript-language-cst-parser/blob/bb36765e325a4ef5368ce5b7dcbb8cb7ed03affa/src/PureScript/CST/Parser/Monad.purs#L103-L108

This will parse as many as it can, but only yielding the last one.
