### ISSUE TITLE
Library for Backends

### ISSUE THREAD

**Issue by mkohlhaas** [natefaubion/purescript-language-cst-parser#29]
Hi Nate,

just a quick question: would this library be useful for writing transpilers/backends for PureScript?

Thank you,
Michael

**Comment by natefaubion** [comment]
This library only parses the surface exact syntax of PureScript. I generally expect it to be used for syntactic tooling (eg. I used it to write purescript-tidy and purescript-tidy-codegen). Most backends consume the compilers corefn target, which is what you get after typechecking and elaboration.

**Comment by mkohlhaas** [comment]
Ok! Got it! Thanks a lot for clarification!
