### ISSUE TITLE
Invalid Identifiers?

### ISSUE THREAD

**Issue by thought2** [natefaubion/purescript-language-cst-parser#50]
Just out of curiosity... why are invalid [Ident](https://github.com/natefaubion/purescript-language-cst-parser/blob/main/src/PureScript/CST/Types.purs#L94)s not ruled out with something like smart constructors?

```hs
ident = Ident "!@# "
```

I've noticed that the DSL in `tidy-codegen` captures this.

**Comment by natefaubion** [comment]
This is a parser. It's not intended to be a correct-by-construction AST. `tidy-codegen` indeed provides that functionality in a very opinionated way.
